parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Asset\VersionStrategy\GulpBusterVersionStrategy:
        arguments:
            - "%kernel.project_dir%/busters.json"
            - "%%s?version=%%s"

    github_client:
        class: '\Github\Client'
        factory: 'App\Service\Github\GithubClientFactory:createClient'

    App\Service\Github\GithubClient:
        public: true
        arguments:
            $client: '@github_client'

    App\Service\Redis\RedisCacheManager:
        public: true
        arguments:
            - '@snc_redis.default'
